# Generated by Django 2.2.24 on 2021-08-06 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/blog/thumbnail/', verbose_name='Blog Thumbnail')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşum Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Adı')),
            ],
            options={
                'verbose_name_plural': 'Bloglar',
                'verbose_name': 'Blog',
            },
        ),
    ]
