# Generated by Django 2.2.24 on 2021-08-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name_plural': 'İletişimler',
                'verbose_name': 'İletişim',
            },
        ),
    ]
